#!/usr/bin/env bash
# Starts local Sui node, creates ADMIN / PLAYER_A / PLAYER_B ed25519 keypairs, funds them.
set -e

SCRIPT_DIR="$(cd "$(dirname "$0")" && pwd)"
source "$SCRIPT_DIR/common.sh"
mkdir -p "$WORKSPACE_DATA"

SUI_CFG="${SUI_CONFIG_DIR:-$HOME/.sui}"
CLIENT_YAML="$SUI_CFG/client.yaml"
KEYSTORE="$SUI_CFG/sui.keystore"

# Ensure clean client config (fixes corrupt volume from previous runs)
mkdir -p "$SUI_CFG"
printf '%s' '[]' > "$KEYSTORE"
cat > "$CLIENT_YAML" << EOF
---
keystore:
  File: $KEYSTORE
envs:
  - alias: local
    rpc: "http://127.0.0.1:9000"
active_env: local
active_address: ~
EOF

printf 'y\n' | sui client switch --env local 2>/dev/null || true

echo "[sui-dev] Starting local Sui network..."
start_local_node

echo "[sui-dev] Creating ed25519 keypairs: ADMIN, PLAYER_A, PLAYER_B..."
for alias in ADMIN PLAYER_A PLAYER_B; do
  if sui keytool export --key-identity "$alias" --json 2>/dev/null | jq -e '.key.suiAddress' >/dev/null 2>&1; then
    echo "[sui-dev] $alias already exists, skipping"
  else
    printf '\n' | sui client new-address ed25519 "$alias" || { echo "[sui-dev] ERROR: Failed to create key $alias" >&2; exit 1; }
  fi
done

sui client addresses
fund_local_accounts

ADMIN=$(sui client active-address)
sui client switch --address PLAYER_A
PLAYER_A=$(sui client active-address)
sui client switch --address PLAYER_B
PLAYER_B=$(sui client active-address)
sui client switch --address ADMIN

echo "[sui-dev] Exporting private keys for TypeScript..."
ADMIN_PRIVATE_KEY=$(sui keytool export --key-identity ADMIN 2>/dev/null | grep -oE 'suiprivkey1[a-z0-9]+' | head -1)
PLAYER_A_PRIVATE_KEY=$(sui keytool export --key-identity PLAYER_A 2>/dev/null | grep -oE 'suiprivkey1[a-z0-9]+' | head -1)
PLAYER_B_PRIVATE_KEY=$(sui keytool export --key-identity PLAYER_B 2>/dev/null | grep -oE 'suiprivkey1[a-z0-9]+' | head -1)

cat > "$WORKSPACE_DATA/.env.sui" << EOF
# Sui localnet – generated by setup-local.sh
SUI_NETWORK=local
SUI_RPC_URL=http://127.0.0.1:9000
ADMIN_ADDRESS=$ADMIN
PLAYER_A_ADDRESS=$PLAYER_A
PLAYER_B_ADDRESS=$PLAYER_B
ADMIN_PRIVATE_KEY=$ADMIN_PRIVATE_KEY
PLAYER_A_PRIVATE_KEY=$PLAYER_A_PRIVATE_KEY
PLAYER_B_PRIVATE_KEY=$PLAYER_B_PRIVATE_KEY
EOF
chmod 600 "$WORKSPACE_DATA/.env.sui"
echo "[sui-dev] Wrote $WORKSPACE_DATA/.env.sui with ADMIN, PLAYER_A, PLAYER_B addresses and private keys."

sui client balance
echo "[sui-dev] Setup complete."
