#!/usr/bin/env bash
# Starts local Sui node, creates ADMIN / PLAYER_A / PLAYER_B ed25519 keypairs, funds them.
set -e

SCRIPT_DIR="$(cd "$(dirname "$0")" && pwd)"
source "$SCRIPT_DIR/common.sh"

echo "[sui-dev] Starting local Sui network..."
sui start --with-faucet --force-regenesis &
SUI_PID=$!
echo $SUI_PID > "$WORKSPACE/.sui-node.pid"

echo "[sui-dev] Waiting for RPC on port 9000..."
for i in $(seq 1 30); do
  if curl -s -o /dev/null http://127.0.0.1:9000 2>/dev/null; then
    echo "[sui-dev] RPC ready."
    break
  fi
  if [ "$i" -eq 30 ]; then
    echo "[sui-dev] RPC did not become ready."
    kill $SUI_PID 2>/dev/null || true
    exit 1
  fi
  sleep 1
done
sleep 3

printf 'y\n' | sui client switch --env local 2>/dev/null || true

echo "[sui-dev] Creating ed25519 keypairs: ADMIN, PLAYER_A, PLAYER_B..."
for alias in ADMIN PLAYER_A PLAYER_B; do
  printf '\n' | sui client new-address ed25519 "$alias" 2>/dev/null || true
done

# List addresses
sui client addresses

echo "[sui-dev] Funding accounts (faucet for each)..."
for alias in ADMIN PLAYER_A PLAYER_B; do
  sui client switch --address "$alias"
  funded=false
  for attempt in 1 2 3; do
    if sui client faucet 2>&1; then
      funded=true
      break
    fi
    echo "[sui-dev] Faucet attempt $attempt failed, retrying in 2s..."
    sleep 2
  done
  if [ "$funded" != "true" ]; then
    echo "[sui-dev] ERROR: Faucet failed for $alias after 3 attempts." >&2
    exit 1
  fi
done

# Prefer ADMIN as default signer
sui client switch --address ADMIN

# Collect addresses for .env.sui
ADMIN=$(sui client active-address)
sui client switch --address PLAYER_A
PLAYER_A=$(sui client active-address)
sui client switch --address PLAYER_B
PLAYER_B=$(sui client active-address)
sui client switch --address ADMIN

cat > "$WORKSPACE/.env.sui" << EOF
# Sui localnet – generated by setup-local.sh
SUI_NETWORK=local
SUI_RPC_URL=http://127.0.0.1:9000
ADMIN_ADDRESS=$ADMIN
PLAYER_A_ADDRESS=$PLAYER_A
PLAYER_B_ADDRESS=$PLAYER_B
EOF
echo "[sui-dev] Wrote $WORKSPACE/.env.sui with ADMIN, PLAYER_A, PLAYER_B addresses."

sui client balance
echo "[sui-dev] Setup complete. Local node PID: $SUI_PID"
