[package]
name = "currency_token"
edition = "2024"

[dependencies]
Sui = { git = "https://github.com/MystenLabs/sui.git", subdir = "crates/sui-framework/packages/sui-framework", rev = "framework/testnet" }

[addresses]
currency_token = "0x0"

# Use -e local for build/publish (local chain ID changes each run)
[environments]
local = "0x0"
