import * as fs from "node:fs";
import * as path from "node:path";
import { getMvrCache } from "./mvrCache.generated";
import { WORLD_TIERS, type WorldMvrName } from "./tenants";

/**
 * Finds each world tier's shared `ObjectRegistry` and `AdminACL` and writes
 * them to `worldObjects.generated.ts`. Run by `pnpm gen:mvr`, after the MVR
 * cache is regenerated.
 *
 * MVR resolves packages and types, not objects. Each tier's world package
 * creates exactly one of each in its `init`, so they're looked up by their MVR
 * type-origin tag. That needs Sui GraphQL (gRPC can't query objects by type),
 * which is why this runs at generation time rather than in the scripts.
 */

const GRAPHQL_URL = process.env.SUI_GRAPHQL_URL || "https://graphql.testnet.sui.io/graphql";
const OUTPUT = path.join(import.meta.dirname, "worldObjects.generated.ts");

const SHARED_OBJECTS = {
    objectRegistry: "object_registry::ObjectRegistry",
    adminAcl: "access::AdminACL",
} as const;

type WorldObjects = Record<keyof typeof SHARED_OBJECTS, string>;

const types = (getMvrCache("testnet") as { types: Record<string, string> }).types;

async function findSingleton(mvrName: WorldMvrName, key: string): Promise<string> {
    const typeTag = types[`${mvrName}::${key}`];
    if (!typeTag) {
        throw new Error(
            `MVR cache has no type-origin entry for "${mvrName}::${key}". ` +
                `Add the tier to MVR_SCAN_SEED in worldTypeKeys.ts and rerun pnpm gen:mvr.`
        );
    }
    const res = await fetch(GRAPHQL_URL, {
        method: "POST",
        headers: { "content-type": "application/json" },
        body: JSON.stringify({
            query: "query($type: String!) { objects(first: 2, filter: { type: $type }) { nodes { address } } }",
            variables: { type: typeTag },
        }),
    });
    if (!res.ok) throw new Error(`GraphQL request failed: ${res.status} ${res.statusText}`);
    const body = (await res.json()) as {
        data?: { objects: { nodes: { address: string }[] } };
        errors?: { message: string }[];
    };
    if (body.errors?.length) throw new Error(`GraphQL error: ${body.errors[0].message}`);
    const nodes = body.data?.objects.nodes ?? [];
    if (nodes.length !== 1) {
        throw new Error(`Expected exactly one ${typeTag} for ${mvrName}, found ${nodes.length}.`);
    }
    return nodes[0].address;
}

async function main() {
    const result: Record<string, WorldObjects> = {};
    for (const mvrName of Object.keys(WORLD_TIERS) as WorldMvrName[]) {
        const entries = await Promise.all(
            Object.entries(SHARED_OBJECTS).map(
                async ([field, key]) => [field, await findSingleton(mvrName, key)] as const
            )
        );
        result[mvrName] = Object.fromEntries(entries) as WorldObjects;
        console.log(`${mvrName}: ${JSON.stringify(result[mvrName])}`);
    }

    fs.writeFileSync(
        OUTPUT,
        `/**
 * Generated by ts-scripts/mvr/gen-world-objects.ts (run \`pnpm gen:mvr\`).
 * Each world tier's shared objects, found on chain by their MVR type. Commit this file.
 */

export const WORLD_OBJECTS: Record<string, { objectRegistry: string; adminAcl: string }> = ${JSON.stringify(result, null, 4)};
`
    );
    console.log(`Wrote ${path.relative(process.cwd(), OUTPUT)}`);
}

main().catch((error) => {
    console.error(error instanceof Error ? error.message : error);
    process.exit(1);
});
