/**
 * This file is automatically generated by the mvr SDK.
 * You can edit this file, but it will be overwritten on the next run.
 * You should check this file in your version control system.
 *
 * Run this script before building your project to ensure that the mvr.ts file stays up to date.
 *
 * You can use this pre-built cache when initializing your Sui client by calling
 * `getMvrCache("mainnet")` or `getMvrCache("testnet")` and passing it as the `overrides` option.
 */

const mainnetResolution = {
    packages: {},
    types: {},
};
const testnetResolution = {
    packages: {
        "@evefrontier/world": "0x7be18d6294e533bedd9a5d70a96ce8d9d4b87a7c74188ba65d3fe966bbed9d92",
    },
    types: {
        "@evefrontier/world::in_game_id::TenantItemId":
            "0x7be18d6294e533bedd9a5d70a96ce8d9d4b87a7c74188ba65d3fe966bbed9d92::in_game_id::TenantItemId",
        "@evefrontier/world::gate::JumpPermit":
            "0x7be18d6294e533bedd9a5d70a96ce8d9d4b87a7c74188ba65d3fe966bbed9d92::gate::JumpPermit",
        "@evefrontier/world::storage_unit::StorageUnit":
            "0x7be18d6294e533bedd9a5d70a96ce8d9d4b87a7c74188ba65d3fe966bbed9d92::storage_unit::StorageUnit",
        "@evefrontier/world::gate::JumpEvent":
            "0x7be18d6294e533bedd9a5d70a96ce8d9d4b87a7c74188ba65d3fe966bbed9d92::gate::JumpEvent",
        "@evefrontier/world::character::Character":
            "0x7be18d6294e533bedd9a5d70a96ce8d9d4b87a7c74188ba65d3fe966bbed9d92::character::Character",
        "@evefrontier/world::object_registry::ObjectRegistry":
            "0x7be18d6294e533bedd9a5d70a96ce8d9d4b87a7c74188ba65d3fe966bbed9d92::object_registry::ObjectRegistry",
        "@evefrontier/world::access::OwnerCap":
            "0x7be18d6294e533bedd9a5d70a96ce8d9d4b87a7c74188ba65d3fe966bbed9d92::access::OwnerCap",
        "@evefrontier/world::gate::Gate":
            "0x7be18d6294e533bedd9a5d70a96ce8d9d4b87a7c74188ba65d3fe966bbed9d92::gate::Gate",
    },
};

export function getMvrCache(network: "mainnet" | "testnet") {
    return network === "mainnet" ? mainnetResolution : testnetResolution;
}
