/**
 * Generated by ts-scripts/mvr/gen-world-objects.ts (run `pnpm gen:mvr`).
 * Each world tier's shared objects, found on chain by their MVR type. Commit this file.
 */

export const WORLD_OBJECTS: Record<string, { objectRegistry: string; adminAcl: string }> = {
    "@evefrontier/world": {
        objectRegistry: "0x8fd47e6e5cf8cb9b789cef26fbb674be819d8abd6afccaf50e95451212f0813a",
        adminAcl: "0xcb4f47804533a80b3854b33b37514ff03b1d7a4debad84bacdbe9fed5bfbf34f",
    },
    "@evefrontier/world-uat": {
        objectRegistry: "0xf37ce91dc59ed7fa5f036e50b65ec99681c36c3e35e89ce5135a77cf116c159d",
        adminAcl: "0x8189c4fdab3a9171f9491154f6f2699a59fe5c8bd870c0e9acf1c91ab4b5d67d",
    },
    "@evefrontier/world-test": {
        objectRegistry: "0xf35ad25648c14b6eb7e098142fc5d68003d9cae1c97a8def8dd3f51ee48b6474",
        adminAcl: "0xc29b604f3a76571d9543697d2ab11e85c46fe308c8c870af10dcc45acfa0ee9f",
    },
};
